#!/bin/bash
sites_directory="hgv_data/config/sites"
active_sites=${sites_directory}"/active/"
inactive_sites=${sites_directory}"/inactive/"

# Write the <site>.yml file for a new project
function build()
{
    # the sites directory where the .yml files for each site is stored
    file_name="$1.yml"
    target_file="${active_sites}${file_name}"

    mkdir -p ${active_sites}

# set up the structure for the YAML file
read -d '' yml_file <<EOF
---
wp:
    enviro: $1
    hhvm_domains:
        - $1-hhvm.hgv.test
    php_domains:
        - $1.hgv.test
EOF

    echo "============================================="
    echo "remove existing ${file_name} file..."
    echo "============================================="
    rm ${target_file}
    echo "============================================="
    echo "removed existing ${file_name}"
    echo "============================================="

    echo "============================================="
    echo "writing ${file_name}..."
    echo "============================================="
    # show the user the contents of the YAML file to be written
    echo "${yml_file}"

    # disable all other sites before provisioning the new site
    echo $(disableAllSites)

    # write the YAML file for the new site
    echo "${yml_file}" >> ${target_file}
    echo "============================================="
    echo "wrote ${file_name}"
    echo "============================================="

    vagrant reload --provision
}

function enable()
{
    target_site="$1.yml"
    mkdir -p ${active_sites}
    
    # disable all other sites by moving them from the active folder to the inactive folder
    echo "============================================="
    echo "disabling all sites"
    echo "============================================="
    shopt -s -q dotglob nullglob
    mv ${active_sites}* ${inactive_sites}

    echo "============================================="
    echo "enabling ${target_site}"
    echo "============================================="
    mv ${inactive_sites}${target_site} ${active_sites}${target_site}
}

function disable()
{
    target_site="$1.yml"
    mkdir -p ${inactive_sites}
    echo "============================================="
    echo "disabling ${target_site}"
    echo "============================================="
    echo $(disableAllSites)
}

function disableAllSites()
{
    mv ${active_sites}* ${inactive_sites}${target_site}
}

$@
